#!/bin/bash

aws ec2 describe-instances --query 'Reservations[].Instances[].[PrivateIpAddress,InstanceId,Tags[?Key==`puppet_role`].Value[]]' --output text | sed 's/None$/None\n/' | sed '$!N;s/\n/ /'

